// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Wordlist$ReBip39 = require("../src/Wordlist.bs.js");

describe("Word List", (function () {
        return Jest.test("should have 2048 words", (function () {
                      return Jest.Expect[/* toBe */2](2048, Jest.Expect[/* expect */0](Wordlist$ReBip39.words.length));
                    }));
      }));

/*  Not a pure module */
